name: Update Keybox

on:
  workflow_dispatch:
    inputs:
      keybox_link:
        description: "Direct link to keybox file"
        required: true
        type: string
      options:
        description: "File type"
        required: true
        type: choice
        options:
          - zip
          - xml
        default: xml
      password:
        description: "Zip password (if needed)"
        required: false
        type: string
        
permissions:
  contents: write
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install 7zip
        if: ${{ github.event.inputs.options == 'zip' }}
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Download file
        run: |
          curl -L "${{ github.event.inputs.keybox_link }}" -o input_file

      - name: Extract file (ZIP only)
        if: ${{ github.event.inputs.options == 'zip' }}
        run: |
          if [ -n "${{ github.event.inputs.password }}" ]; then
            7z x -y -p"${{ github.event.inputs.password }}" input_file
          else
            7z x -y input_file
          fi


      - name: Commit & Push keybox
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add input_file

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update Yurikey"
          git push
